### ISSUE TITLE
Lookyloo crash on new capture if no user-agent list

### ISSUE THREAD

**Issue by FafnerKeyZee** [Lookyloo/lookyloo#262]
## Expected behavior
Can submit a new capture

## Actual behavior
Crash and can't submit a new caputre

## Steps to reproduce the problem

1. Use new install without any user-agent :p

## Additional information

```
ERROR:web:Exception on /capture [GET]
Traceback (most recent call last):
  File "/home/fafner/.cache/pypoetry/virtualenvs/lookyloo-sEu34To5-py3.8/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fafner/.cache/pypoetry/virtualenvs/lookyloo-sEu34To5-py3.8/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fafner/.cache/pypoetry/virtualenvs/lookyloo-sEu34To5-py3.8/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fafner/.cache/pypoetry/virtualenvs/lookyloo-sEu34To5-py3.8/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/fafner/.cache/pypoetry/virtualenvs/lookyloo-sEu34To5-py3.8/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fafner/.cache/pypoetry/virtualenvs/lookyloo-sEu34To5-py3.8/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fafner/lookyloo/website/web/__init__.py", line 707, in capture_web
    for ua in user_agents.pop('by_frequency'):
KeyError: 'by_frequency'
```

**Comment by Rafiot** [comment]
This is very odd and I have a hard time figuring out how this can happen: there are user agents in `<homedir>/user_agents/` and they should be used as fallback. And if there are none, the call to `get_user_agents` should fail.

I'm pushing a slight fix that will make the code slightly better, but this shouldn't solve the problem of the key missing in the dict. Which commit are you on, but this is also not where this line of code is now.

**Comment by FafnerKeyZee** [comment]
After full cleaning and starting with a fresh install all is running fine.
So I guess an error during the install process.
As I'm not able to recreate the error, we can consider it as closed.
